### PR TITLE
Fix select command

### LINKED ISSUE #62: Link new UI to deck commands
New buttons included in the latest PR that has 2 buttons in the menu bar to switch between decks.  Functions in MainWindow.java needs to be changed such that clicking those buttons in the GUI will switch user decks

### LINKED ISSUE #70: Select Command: UI
Select does not change the UI to display entries in the selected deck

### PR DESCRIPTION
**Pull request by GabrielSimbingyang**
Select command bug is still not fixed but I have found the issue. 

These are the things I have done:
I added a stub deck with stub entries in line 186 - 194 of the ModelManager.java. 
I modified SelectCommand.java to also call an additional function replaceEntryList() (in ModelManager line 157)
Reduced the GUI height initialization (just for convenience)

These are the things I found out: 
1. The deck UI display is tied to AddressBook.java field UniqueDeckList decks
2. The Entry UI display is tied to the STUB Deck object that is created . To be more specific, it is tied to the field UniqueEntryList entries. 
3. When you launch the program, you can add decks and you can add entries and it will update the GUI 
4. But when you use the old select command, ModelManager gets told to operate on the selected deck and stops operating on the stub deck
5. Remember when I said the UI is tied to the stub decks UniqueEntryList field? This means that even though you are updating the selected decks list, nothing  changes in the UI because nothing changes in the stub's UniqueEntryList 
6. When you select the original deck back (by typing select 1), you can start to add entries back and it will update the GUI accordingly
7. I added some things to attempt solution B below in ModelManger.java line 159-164, it is not working

To solve the bug:
Solution A: Hopefully one of us can help figure out why the initialization tied to the stub field. If we can find out how to switch the field to another location, we can create and maintain a observedDeckList and observedEntryList in AddressBook.java 
Solution B (worse solution): We can maintain the existence of the stub and just operate on the list there -> it means maintaining poor OOP code

### CODE REVIEW

**Comment by GabrielSimbingyang** [comment]
@vigneshbhuvan-nus  please fix your CI checks next time before merging. It really screwed over the test @IlyaRin had written and I have no idea how to fix it.

**Comment by geoboom** [comment]
Yo! Regarding this:

> But when you use the old select command, ModelManager gets told to operate on the selected deck and stops operating on the stub deck
> Remember when I said the UI is tied to the stub decks UniqueEntryList field? This means that even though you are updating the selected decks list, nothing changes in the UI because nothing changes in the stub's UniqueEntryList

Could you please provide steps to reproduce the issue? What I did are as follow:

I resolved the concurrent modification issue caused by `replaceEntryList()` in `ModelManager.java` by changing the method body to:
```java
public void replaceEntryList() {
    observedDeck.setEntries(getCurrentDeck().getEntries());
}
```
I don't think removing all entries in `observedDeck.entries` is necessary since `observedDeck.setEntries(...)` will directly replace the old `entries` with new `entries`. Java garbage collector will handle the rest.

Next, I launched the program and issued the following command:
```
add w/test_word t/test_translate
```
and expected to see no update to the UI. However, I saw my new entry appear beneath all the stub entries.

I re-launched the program and tested these commands:
```
select 1
add w/test_word t/test_translate
```
and saw my new entry appear beneath all the stub entries too.

EDIT: fix stupid indent kena copied over from idea

**Comment by GabrielSimbingyang** [comment]
### Select command has been fixed

**Fixing the UI**

I found out that during initialization, the wrong output of the method getFilteredEntryList() from ModelManager.java gets passed to the UI. This meant that the UI was watching the first decks UniqueEntryList. 

I changed it so that now the UI watches observedEntries from the PUBLIC field in AddressBook.java. 

_Hence, any changes to observedEntries from AddressBook.java will directly result in a change to the GUI._

**Select Command**

I edited the Select Command to now directly change the observedEntries, the low level details are documented in the code. 

Essentially, it creates a copy of the observedEntries, then deletes the original entries. It then fills observedEntries with entries of the selected command. The reason why we have to create a direct copy is to avoid the concurrent modification exception. Not the best performance O(n^2 * m) but performance can be optimized later.

**Issues**

The modification to AddressBook.observedEntries is done directly (because observedEntries is a public field), we should change this in the future. 

Now edit command has to be updated, please refer to the code I have written to get an idea on how to do it.

List command can be deleted as well

Clear command needs to be updated as well (should it clear decks or clear entries?)


**Homework for you guys:** 
- Fix the edit command such that it displays the edit command (for now, it only edits the deck's entrybut doesn't show it)
- Determine if list command needs to be deleted and delete/not delete it accordingly
- Do the same for clear command

**Comment by MelanieNPS** [comment]
> List command can be deleted as well
> Clear command needs to be updated as well (should it clear decks or clear entries?)
> * Fix the edit command such that it displays the edit command (for now, it only edits the deck's entry but doesn't show it)

Looks good to me. Will add edit command, clear command as issues. List command probably is still needed only for entries since users are able to filter

**Pull request merged**
